# Generated by Django 3.0.6 on 2020-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200610_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=-1),
        ),
    ]
