# Generated by Django 3.0.6 on 2020-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200612_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight')], default='lose_weight', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_units',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=3),
        ),
    ]
