# Generated by Django 3.0.6 on 2020-06-14 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200614_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('couch_potato', 'Couch potato'), ('lightly_active', 'Lightly active'), ('moderately_active', 'Moderately active'), ('pretty_active', 'Pretty active'), ('active_is_your_middle_name', 'Active is your middle name')], default='low', max_length=27),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Lose weight'), ('maintain_weight', 'Maintain weight'), ('gain_weight', 'Gain weight')], default='lose_weight', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=-1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
