# Generated by Django 3.0.6 on 2020-11-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('couch_potato', 'Couch potato'), ('lightly_active', 'Lightly active'), ('moderately_active', 'Moderately active'), ('pretty_active', 'Pretty active'), ('extremely_active', 'Extremely active')], default='low', max_length=27),
        ),
    ]
