# Generated by Django 3.0.6 on 2020-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='user_meal_plan',
            field=models.TextField(default='{}'),
        ),
    ]
