# Generated by Django 3.0.6 on 2020-12-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_meals_user_meal_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealsprofile',
            name='num_of_meals',
        ),
        migrations.RemoveField(
            model_name='mealsprofile',
            name='num_of_snacks',
        ),
    ]
