# Generated by Django 3.0.6 on 2021-01-16 22:38

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210116_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsprofile',
            name='calories',
            field=models.IntegerField(default=users.models.MealsProfile.calculated_calories, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
