# Generated by Django 3.0.6 on 2021-01-16 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210116_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsprofile',
            name='num_of_snacks',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
