# Generated by Django 3.0.6 on 2021-01-17 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_meals_user_saved_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='user_num_of_saved_meals',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
