# Generated by Django 3.0.6 on 2021-01-23 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_meals_user_num_of_saved_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=-1, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
