# Generated by Django 3.1.5 on 2021-01-27 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_feet_seg',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inches_seg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_height_units',
            field=models.CharField(choices=[('cm', 'cm'), ('feet_and_inches', 'feet and inches')], default='cm', max_length=16),
        ),
    ]
