# Generated by Django 3.1.5 on 2021-01-27 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210127_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, default=-1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_feet_seg',
            field=models.IntegerField(blank=True, default=-1, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_inches_seg',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
