# Generated by Django 3.0.6 on 2020-06-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caloric_value', models.IntegerField(default=-1)),
                ('grams_of_fat', models.IntegerField(default=-1)),
                ('grams_of_protien', models.IntegerField(default=-1)),
                ('grams_of_carbs', models.IntegerField(default=-1)),
                ('title', models.CharField(default='Meal 1', max_length=6)),
            ],
        ),
    ]
