# Generated by Django 3.0.6 on 2020-12-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0003_mealplan_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='owner',
        ),
    ]
